/*
 * EMI Calculator Service API
 * API specification of the EMI calculator microservice.
 *
 * OpenAPI spec version: 1.0
 * Contact: nitish.kashyap44@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.microservice.emicalculator.api;

import java.math.BigDecimal;
import java.util.Objects;

import javax.validation.Valid;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Min;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Duration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-19T16:46:45.957+05:30[Asia/Calcutta]")
@XmlRootElement(name = "Duration")
@XmlAccessorType(XmlAccessType.FIELD)

public class Duration {
  @XmlElement(name = "numberOfDays")
  public static final String SERIALIZED_NAME_NUMBER_OF_DAYS = "numberOfDays";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_DAYS)
  private Integer numberOfDays;

  @XmlElement(name = "numberOfMonths")
  public static final String SERIALIZED_NAME_NUMBER_OF_MONTHS = "numberOfMonths";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_MONTHS)
  private BigDecimal numberOfMonths;

  @XmlElement(name = "numberOfYears")
  public static final String SERIALIZED_NAME_NUMBER_OF_YEARS = "numberOfYears";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_YEARS)
  private BigDecimal numberOfYears;

  public Duration numberOfDays(Integer numberOfDays) {
    this.numberOfDays = numberOfDays;
    return this;
  }

   /**
   * It denotes total number of pieces in the shipment.
   * minimum: 1
   * @return numberOfDays
  **/
 @Min(1)  @ApiModelProperty(example = "100", value = "It denotes total number of pieces in the shipment.")
  public Integer getNumberOfDays() {
    return numberOfDays;
  }

  public void setNumberOfDays(Integer numberOfDays) {
    this.numberOfDays = numberOfDays;
  }

  public Duration numberOfMonths(BigDecimal numberOfMonths) {
    this.numberOfMonths = numberOfMonths;
    return this;
  }

   /**
   * Get numberOfMonths
   * @return numberOfMonths
  **/
  @Valid
  @ApiModelProperty(example = "1000", value = "")
  public BigDecimal getNumberOfMonths() {
    return numberOfMonths;
  }

  public void setNumberOfMonths(BigDecimal numberOfMonths) {
    this.numberOfMonths = numberOfMonths;
  }

  public Duration numberOfYears(BigDecimal numberOfYears) {
    this.numberOfYears = numberOfYears;
    return this;
  }

   /**
   * Get numberOfYears
   * minimum: 0
   * maximum: 60
   * @return numberOfYears
  **/
  @Valid
 @DecimalMin("0") @DecimalMax("60")  @ApiModelProperty(value = "")
  public BigDecimal getNumberOfYears() {
    return numberOfYears;
  }

  public void setNumberOfYears(BigDecimal numberOfYears) {
    this.numberOfYears = numberOfYears;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Duration duration = (Duration) o;
    return Objects.equals(this.numberOfDays, duration.numberOfDays) &&
        Objects.equals(this.numberOfMonths, duration.numberOfMonths) &&
        Objects.equals(this.numberOfYears, duration.numberOfYears);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfDays, numberOfMonths, numberOfYears);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Duration {\n");
    
    sb.append("    numberOfDays: ").append(toIndentedString(numberOfDays)).append("\n");
    sb.append("    numberOfMonths: ").append(toIndentedString(numberOfMonths)).append("\n");
    sb.append("    numberOfYears: ").append(toIndentedString(numberOfYears)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

