/*
 * EMI Calculator Service API
 * API specification of the EMI calculator microservice.
 *
 * OpenAPI spec version: 1.0
 * Contact: nitish.kashyap44@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.microservice.emicalculator.api;

import java.util.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * EMI
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-19T16:46:45.957+05:30[Asia/Calcutta]")
@XmlRootElement(name = "EMI")
@XmlAccessorType(XmlAccessType.FIELD)

public class EMI {
  @XmlElement(name = "emiAmountInLoanPayableCurr")
  public static final String SERIALIZED_NAME_EMI_AMOUNT_IN_LOAN_PAYABLE_CURR = "emiAmountInLoanPayableCurr";
  @SerializedName(SERIALIZED_NAME_EMI_AMOUNT_IN_LOAN_PAYABLE_CURR)
  private String emiAmountInLoanPayableCurr;

  @XmlElement(name = "totalpayableamountInLoanPayableCurr")
  public static final String SERIALIZED_NAME_TOTALPAYABLEAMOUNT_IN_LOAN_PAYABLE_CURR = "totalpayableamountInLoanPayableCurr";
  @SerializedName(SERIALIZED_NAME_TOTALPAYABLEAMOUNT_IN_LOAN_PAYABLE_CURR)
  private String totalpayableamountInLoanPayableCurr;

  @XmlElement(name = "totalinterestInLoanPayableCurr")
  public static final String SERIALIZED_NAME_TOTALINTEREST_IN_LOAN_PAYABLE_CURR = "totalinterestInLoanPayableCurr";
  @SerializedName(SERIALIZED_NAME_TOTALINTEREST_IN_LOAN_PAYABLE_CURR)
  private String totalinterestInLoanPayableCurr;

  public EMI emiAmountInLoanPayableCurr(String emiAmountInLoanPayableCurr) {
    this.emiAmountInLoanPayableCurr = emiAmountInLoanPayableCurr;
    return this;
  }

   /**
   * Get emiAmountInLoanPayableCurr
   * @return emiAmountInLoanPayableCurr
  **/
  @ApiModelProperty(value = "")
  public String getEmiAmountInLoanPayableCurr() {
    return emiAmountInLoanPayableCurr;
  }

  public void setEmiAmountInLoanPayableCurr(String emiAmountInLoanPayableCurr) {
    this.emiAmountInLoanPayableCurr = emiAmountInLoanPayableCurr;
  }

  public EMI totalpayableamountInLoanPayableCurr(String totalpayableamountInLoanPayableCurr) {
    this.totalpayableamountInLoanPayableCurr = totalpayableamountInLoanPayableCurr;
    return this;
  }

   /**
   * Get totalpayableamountInLoanPayableCurr
   * @return totalpayableamountInLoanPayableCurr
  **/
  @ApiModelProperty(value = "")
  public String getTotalpayableamountInLoanPayableCurr() {
    return totalpayableamountInLoanPayableCurr;
  }

  public void setTotalpayableamountInLoanPayableCurr(String totalpayableamountInLoanPayableCurr) {
    this.totalpayableamountInLoanPayableCurr = totalpayableamountInLoanPayableCurr;
  }

  public EMI totalinterestInLoanPayableCurr(String totalinterestInLoanPayableCurr) {
    this.totalinterestInLoanPayableCurr = totalinterestInLoanPayableCurr;
    return this;
  }

   /**
   * Get totalinterestInLoanPayableCurr
   * @return totalinterestInLoanPayableCurr
  **/
  @ApiModelProperty(value = "")
  public String getTotalinterestInLoanPayableCurr() {
    return totalinterestInLoanPayableCurr;
  }

  public void setTotalinterestInLoanPayableCurr(String totalinterestInLoanPayableCurr) {
    this.totalinterestInLoanPayableCurr = totalinterestInLoanPayableCurr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EMI EMI = (EMI) o;
    return Objects.equals(this.emiAmountInLoanPayableCurr, EMI.emiAmountInLoanPayableCurr) &&
        Objects.equals(this.totalpayableamountInLoanPayableCurr, EMI.totalpayableamountInLoanPayableCurr) &&
        Objects.equals(this.totalinterestInLoanPayableCurr, EMI.totalinterestInLoanPayableCurr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emiAmountInLoanPayableCurr, totalpayableamountInLoanPayableCurr, totalinterestInLoanPayableCurr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EMI {\n");
    
    sb.append("    emiAmountInLoanPayableCurr: ").append(toIndentedString(emiAmountInLoanPayableCurr)).append("\n");
    sb.append("    totalpayableamountInLoanPayableCurr: ").append(toIndentedString(totalpayableamountInLoanPayableCurr)).append("\n");
    sb.append("    totalinterestInLoanPayableCurr: ").append(toIndentedString(totalinterestInLoanPayableCurr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

