/*
 * EMI Calculator Service API
 * API specification of the EMI calculator microservice.
 *
 * OpenAPI spec version: 1.0
 * Contact: nitish.kashyap44@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.microservice.emicalculator.api;

import java.util.Objects;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * EmiCalculatorServiceRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-19T16:46:45.957+05:30[Asia/Calcutta]")
@XmlRootElement(name = "EmiCalculatorServiceRequest")
@XmlAccessorType(XmlAccessType.FIELD)

public class EmiCalculatorServiceRequest {
  @XmlElement(name = "emiCalculatorRequest")
  public static final String SERIALIZED_NAME_EMI_CALCULATOR_REQUEST = "emiCalculatorRequest";
  @SerializedName(SERIALIZED_NAME_EMI_CALCULATOR_REQUEST)
  private EmiCalculatorRequest emiCalculatorRequest = null;

  public EmiCalculatorServiceRequest emiCalculatorRequest(EmiCalculatorRequest emiCalculatorRequest) {
    this.emiCalculatorRequest = emiCalculatorRequest;
    return this;
  }

   /**
   * Get emiCalculatorRequest
   * @return emiCalculatorRequest
  **/
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  public EmiCalculatorRequest getEmiCalculatorRequest() {
    return emiCalculatorRequest;
  }

  public void setEmiCalculatorRequest(EmiCalculatorRequest emiCalculatorRequest) {
    this.emiCalculatorRequest = emiCalculatorRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmiCalculatorServiceRequest emiCalculatorServiceRequest = (EmiCalculatorServiceRequest) o;
    return Objects.equals(this.emiCalculatorRequest, emiCalculatorServiceRequest.emiCalculatorRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emiCalculatorRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmiCalculatorServiceRequest {\n");
    
    sb.append("    emiCalculatorRequest: ").append(toIndentedString(emiCalculatorRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

