/*
 * EMI Calculator Service API
 * API specification of the EMI calculator microservice.
 *
 * OpenAPI spec version: 1.0
 * Contact: nitish.kashyap44@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.microservice.emicalculator.api;

import java.util.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * EmiCalculatorResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-19T16:46:45.957+05:30[Asia/Calcutta]")
@XmlRootElement(name = "EmiCalculatorResponse")
@XmlAccessorType(XmlAccessType.FIELD)

public class EmiCalculatorResponse {
  @XmlElement(name = "emiDetails")
  public static final String SERIALIZED_NAME_EMI_DETAILS = "emiDetails";
  @SerializedName(SERIALIZED_NAME_EMI_DETAILS)
  private EmiDetails emiDetails = null;

  public EmiCalculatorResponse emiDetails(EmiDetails emiDetails) {
    this.emiDetails = emiDetails;
    return this;
  }

   /**
   * Get emiDetails
   * @return emiDetails
  **/
  @ApiModelProperty(value = "")
  public EmiDetails getEmiDetails() {
    return emiDetails;
  }

  public void setEmiDetails(EmiDetails emiDetails) {
    this.emiDetails = emiDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmiCalculatorResponse emiCalculatorResponse = (EmiCalculatorResponse) o;
    return Objects.equals(this.emiDetails, emiCalculatorResponse.emiDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emiDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmiCalculatorResponse {\n");
    
    sb.append("    emiDetails: ").append(toIndentedString(emiDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

